POST http://localhost:8000/api-auth/token/ HTTP/1.1
content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:8000/api-auth/token/ HTTP/1.1
content-Type: application/json

{
    "username": "admin",
    "password": "badpass"
}

###


POST http://localhost:8000/api/client/ HTTP/1.1
content-Type: application/json



###


GET http://localhost:8000/api/weather/?city=moscow&date=2023-03-20 HTTP/1.1
content-Type: application/json

###

GET http://localhost:8000/api/client/ HTTP/1.1
content-Type: application/json


