# Generated by Django 4.1.7 on 2023-03-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_photo_image_photo_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_url',
            new_name='image',
        ),
    ]
