# Generated by Django 4.1.7 on 2023-03-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
